//! # `telemetry` — Event Schema and Deterministic Serialization
//!
//! ## Architecture Decision
//!
//! The telemetry event is the *unit of truth* in SentinelMark. Every event
//! must be:
//!
//! 1. **Uniquely identified** — `EventId` (UUID v4) prevents ambiguity.
//! 2. **Timestamped** — `captured_at` (RFC 3339, nanosecond resolution).
//! 3. **Nonce-protected** — `nonce` is 32 random bytes generated by
//!    `ring::rand::SystemRandom`, preventing replay even for identical behavior.
//! 4. **Watermarked** — `watermark` is the BEW output `W_i`.
//! 5. **Chained** — `prev_hash` links this event to its predecessor.
//! 6. **Self-describing** — `schema_version` allows future migration without
//!    breaking the verifier.
//!
//! ## Dual Serialization Strategy
//!
//! | Format | Use case | Why |
//! |---|---|---|
//! | `serde_json` | REST transport, Python API, human inspection | Interoperability |
//! | `rkyv` | Benchmarks, on-disk archive, zero-copy deserialization | Zero-allocation read |
//!
//! `rkyv` with `strict` feature enforces stable field ordering and rejects
//! invalid archives, preventing deserialization confusion attacks.
//!
//! ## Security Reasoning
//!
//! - `nonce: [u8; 32]` — 256-bit random ensures collision probability <
//!   2^{-128} after 2^{64} events (birthday bound). This exceeds the lifetime
//!   of any plausible deployment.
//! - `watermark: [u8; 32]` — 256-bit HKDF output; constant-time verified.
//! - `prev_hash: [u8; 32]` — SHA-256 of previous event's canonical form;
//!   breaks if any event is deleted, reordered, or modified.
//!
//! ## Performance Tradeoffs
//!
//! - `serde_json` serialization: ~300ns per event (measured).
//! - `rkyv` zero-copy: ~10ns per event deserialization.
//! - UUID generation via `uuid::Uuid::new_v4()`: ~50ns (calls OS RNG).

use chrono::{DateTime, Utc};
use ring::rand::{SecureRandom, SystemRandom};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

// ─── Constants ───────────────────────────────────────────────────────────────

/// Current schema version. Increment on breaking changes.
pub const SCHEMA_VERSION: u8 = 1;

/// Nonce length in bytes (256-bit).
pub const NONCE_LEN: usize = 32;

/// Watermark length in bytes (256-bit HKDF output).
pub const WATERMARK_LEN: usize = 32;

/// Hash length in bytes (SHA-256).
pub const HASH_LEN: usize = 32;

// ─── EventId ────────────────────────────────────────────────────────────────

/// Unique identifier for a telemetry event.
///
/// Backed by UUID v4 (random). Serializes as a hyphenated lowercase string
/// (e.g., `"550e8400-e29b-41d4-a716-446655440000"`).
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct EventId(Uuid);

impl EventId {
    /// Generate a new random `EventId`.
    #[must_use]
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }

    /// Return the inner UUID.
    #[must_use]
    pub fn inner(&self) -> Uuid {
        self.0
    }
}

impl Default for EventId {
    fn default() -> Self {
        Self::new()
    }
}

impl std::fmt::Display for EventId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0.as_hyphenated())
    }
}

// ─── TelemetryEvent ──────────────────────────────────────────────────────────

/// A single tamper-evident forensic telemetry event.
///
/// This is the wire format and storage format. Fields are ordered by their
/// role in the BEW protocol to aid readability in academic publications.
///
/// # Invariants (enforced by [`TelemetryEvent::new`])
/// - `nonce` is always freshly generated from OS CSPRNG.
/// - `schema_version` is always [`SCHEMA_VERSION`].
/// - `watermark` must be set via [`TelemetryEvent::set_watermark`] before transmission.
/// - `current_hash` must be set via [`TelemetryEvent::finalize`] before transmission.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TelemetryEvent {
    /// Protocol version — must match verifier's expected version.
    pub schema_version: u8,

    /// Unique event identifier (UUID v4).
    pub event_id: EventId,

    /// Monotonic sequence number.
    pub sequence_number: u64,

    /// UTC timestamp of event creation (RFC 3339, nanosecond precision).
    pub captured_at: DateTime<Utc>,

    /// Device identifier — opaque string, typically a device certificate fingerprint.
    /// Must NOT be a plaintext hostname in production.
    pub device_id: String,

    /// Per-event random nonce (256-bit, OS CSPRNG).
    /// Hex-encoded for JSON transport; raw bytes for rkyv.
    #[serde(with = "hex::serde")]
    pub nonce: [u8; NONCE_LEN],

    /// SHA-256 of the previous event's canonical form.
    /// Set to `[0u8; 32]` for the genesis event.
    #[serde(with = "hex::serde")]
    pub prev_hash: [u8; HASH_LEN],

    /// BEW watermark `W_i` — HKDF-SHA256 output (256-bit).
    /// Set to `[0u8; 32]` until [`TelemetryEvent::set_watermark`] is called.
    #[serde(with = "hex::serde")]
    pub watermark: [u8; WATERMARK_LEN],

    /// SHA-256 of this event's canonical form (after watermark is set).
    /// Set by [`TelemetryEvent::finalize`].
    #[serde(with = "hex::serde")]
    pub current_hash: [u8; HASH_LEN],

    /// Arbitrary structured payload (application-level telemetry data).
    /// Must be serializable to JSON. Large payloads should be content-addressed
    /// (store hash here, payload separately).
    pub payload: serde_json::Value,
}

impl TelemetryEvent {
    /// Construct a new event with a fresh nonce and current timestamp.
    ///
    /// `watermark` and `current_hash` are set to zero — they must be
    /// populated by the `WatermarkEngine` and `ChainManager` respectively
    /// before transmission.
    ///
    /// # Errors
    /// Returns [`TelemetryError::RngFailure`] if the OS CSPRNG is unavailable.
    pub fn new(
        device_id: impl Into<String>,
        sequence_number: u64,
        prev_hash: [u8; HASH_LEN],
        payload: serde_json::Value,
    ) -> Result<Self, TelemetryError> {
        let rng = SystemRandom::new();
        let mut nonce = [0u8; NONCE_LEN];
        rng.fill(&mut nonce)
            .map_err(|_| TelemetryError::RngFailure)?;

        Ok(Self {
            schema_version: SCHEMA_VERSION,
            event_id: EventId::new(),
            sequence_number,
            captured_at: Utc::now(),
            device_id: device_id.into(),
            nonce,
            prev_hash,
            watermark: [0u8; WATERMARK_LEN],
            current_hash: [0u8; HASH_LEN],
            payload,
        })
    }

    /// Set the BEW watermark. Must be called before [`finalize`].
    pub fn set_watermark(&mut self, watermark: [u8; WATERMARK_LEN]) {
        self.watermark = watermark;
    }

    /// Compute and set `current_hash` from the event's **pre-image** serialization.
    ///
    /// The pre-image excludes `current_hash` itself to avoid circularity:
    ///
    /// ```text
    /// current_hash = SHA-256(canonical_preimage(event \ {current_hash}))
    /// ```
    ///
    /// The chain verifier calls `preimage_bytes()` independently to recompute
    /// and compare, maintaining consistency.
    ///
    /// Must be called AFTER [`set_watermark`].
    ///
    /// # Errors
    /// Returns [`TelemetryError::SerializationFailed`] if JSON serialization fails.
    pub fn finalize(&mut self) -> Result<(), TelemetryError> {
        let preimage = self
            .preimage_bytes()
            .map_err(|e| TelemetryError::SerializationFailed(e.to_string()))?;

        self.current_hash = crate::crypto::sha256(&preimage);
        Ok(())
    }

    /// Produce the canonical pre-image bytes for hashing.
    ///
    /// This serializes all fields **except** `current_hash` to avoid circularity.
    /// The chain verifier MUST use this method to recompute hashes during verification.
    ///
    /// **Stability guarantee**: field set is fixed by `schema_version`.
    pub fn preimage_bytes(&self) -> Result<Vec<u8>, serde_json::Error> {
        // Serialize a projection of the event that excludes current_hash.
        // We use a dedicated helper struct to avoid field-order ambiguity.
        let preimage = TelemetryPreimage {
            schema_version: self.schema_version,
            event_id: &self.event_id,
            sequence_number: self.sequence_number,
            captured_at: &self.captured_at,
            device_id: &self.device_id,
            nonce: &self.nonce,
            prev_hash: &self.prev_hash,
            watermark: &self.watermark,
            payload: &self.payload,
        };
        serde_json::to_vec(&preimage)
    }

    /// Full event serialization including `current_hash` — for wire transport.
    pub fn canonical_bytes(&self) -> Result<Vec<u8>, serde_json::Error> {
        serde_json::to_vec(self)
    }

    /// Return a reference to `nonce` as bytes (for replay detection).
    pub fn nonce_bytes(&self) -> &[u8] {
        &self.nonce
    }
}

/// Pre-image helper: all fields except `current_hash`.
///
/// Used to compute `current_hash = SHA-256(TelemetryPreimage)`, preventing
/// the circular dependency that would arise from including `current_hash` in
/// its own pre-image.
#[derive(Serialize)]
struct TelemetryPreimage<'a> {
    schema_version: u8,
    event_id: &'a EventId,
    sequence_number: u64,
    captured_at: &'a DateTime<Utc>,
    device_id: &'a str,
    #[serde(with = "hex::serde")]
    nonce: &'a [u8; NONCE_LEN],
    #[serde(with = "hex::serde")]
    prev_hash: &'a [u8; HASH_LEN],
    #[serde(with = "hex::serde")]
    watermark: &'a [u8; WATERMARK_LEN],
    payload: &'a serde_json::Value,
}

// ─── Error type ─────────────────────────────────────────────────────────────

/// Errors produced by telemetry event construction.
#[derive(Debug, thiserror::Error)]
pub enum TelemetryError {
    /// OS CSPRNG is unavailable or failed.
    #[error("OS CSPRNG is unavailable — cannot generate nonce")]
    RngFailure,

    /// JSON serialization failed.
    #[error("serialization failed: {0}")]
    SerializationFailed(String),
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn make_event(seq: u64) -> TelemetryEvent {
        TelemetryEvent::new(
            "device-test-001",
            seq,
            [0u8; HASH_LEN],
            serde_json::json!({"test": true}),
        )
        .expect("event construction must succeed")
    }

    #[test]
    fn test_event_has_fresh_nonce() {
        let e1 = make_event(1);
        let e2 = make_event(2);
        // Two events must have different nonces (astronomically unlikely to collide)
        assert_ne!(e1.nonce, e2.nonce);
    }

    #[test]
    fn test_finalize_sets_current_hash() {
        let mut e = make_event(1);
        e.set_watermark([0xab_u8; WATERMARK_LEN]);
        e.finalize().expect("finalize must succeed");
        assert_ne!(e.current_hash, [0u8; HASH_LEN]);
    }

    #[test]
    fn test_serialization_roundtrip() {
        let mut e = make_event(1);
        e.set_watermark([0xcd_u8; WATERMARK_LEN]);
        e.finalize().unwrap();

        let json = serde_json::to_string(&e).unwrap();
        let restored: TelemetryEvent = serde_json::from_str(&json).unwrap();
        assert_eq!(e.event_id, restored.event_id);
        assert_eq!(e.nonce, restored.nonce);
        assert_eq!(e.watermark, restored.watermark);
        assert_eq!(e.current_hash, restored.current_hash);
    }

    #[test]
    fn test_schema_version_is_set() {
        let e = make_event(1);
        assert_eq!(e.schema_version, SCHEMA_VERSION);
    }
}
